language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm

node_js:
  - '9'

script:
  - yarn build

deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    verbose: true
    skip-cleanup: true
    keep-history: true
    local-dir: public
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: 
      - secure: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET
    local_dir: public
    skip_cleanup: true
    edge: true
    on:
      branch: s3-branch




