locale: "pt-br"
backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: feature/gatsbyv2 # Branch to update
  repo: rdricco/renatoricco.com # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets
# publish_mode: editorial_workflow
# logo_url: https://elated-wozniak-10af2e.netlify.com/assets/reallybigsky.jpg

site_url: https://elated-wozniak-10af2e.netlify.com/
display_url: https://elated-wozniak-10af2e.netlify.com/

collections:
  - name: portfolio
    label: "works"
    folder: "content/works"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Preview Image", name: "preview", widget: "image" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
